name: cinematic
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  provider: ^6.1.4
  path: ^1.9.0
  path_provider: ^2.1.5
  crypto: ^3.0.3
  sqflite: ^2.4.2
  flutter_launcher_icons: ^0.14.3
  connectivity_plus: ^6.1.3
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets: 
    - images/cinematic_icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/cinematic_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21